# Generated by Django 4.1.7 on 2023-02-28 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
