# Generated by Django 4.1.7 on 2023-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contato_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='foto',
            field=models.ImageField(default=1, upload_to='fotos'),
            preserve_default=False,
        ),
    ]
