# Generated by Django 4.1.7 on 2023-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0009_remove_contato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ManyToManyField(related_name='contato_categoria', to='contatos.categoria'),
        ),
    ]
