# Generated by Django 4.1.7 on 2023-03-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0010_contato_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='categoria',
        ),
        migrations.AddField(
            model_name='contato',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contatos.categoria'),
        ),
    ]
